name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Semver - major, minor, patch"
        default: "patch"

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
    - name: Semver deployment
      run: |
        echo "Hello ${{ github.event.inputs.name }}"